name: Build and Deploy Node.js Azure Function App

on:
  push:
    branches: [ "main" ]

env:
  NODE_VERSION: '20.x'
  AZURE_FUNCTIONAPP_NAME: 'finance-app-cne'  # Your Function App name from Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './back-end'  # Path to function app project root

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/package-lock.json'

    - name: Install, Build, and Test
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
